
services:
  db-oracle:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: db_oracle
    environment:
      - ORACLE_PWD=${ORACLE_PASSWORD}
      - ORACLE_CHARACTERSET=${ORACLE_CHARACTERSET}
    ports:
      - "${ORACLE_PORT}:1521"
      - "${ORACLE_EM_PORT}:5500"
    volumes:
      - oradata:/opt/oracle/oradata
    restart: unless-stopped

volumes:
  oradata: